services:
  postgres:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: rat
      POSTGRES_DB: auth_service
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rat -d auth_service"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
