version: '3'

tasks:
  build:
    cmds:
      - go mod tidy
      - go mod verify
      - go build -o

  tests:
    cmds:
      - go test --race ./...

  test-by-name:
    cmds:
      - go test --race --run "{{.TNAME}}" ./...
