version: '3'

env:
  APP_NETWORK: auth-service_default
  POSTGRES_PASSWORD: secret
  POSTGRES_USER: rat
  POSTGRES_DB: auth_service
  POSTGRES_MIGRATE_NUMBER: 1

tasks:
  build:
    cmds:
      - go mod tidy
      - go mod verify
      - CGO_ENABLED=0 GOOS=linux go build -o ./.bin/auth-service ./cmd/main.go
      - chmod +x .bin/auth-service

  tests:
    cmds:
      - go test --race ./...

  test-by-name:
    cmds:
      - go test --race --run "{{.TNAME}}" ./...

  compose-up:
    cmds:
      - task: build
      - docker compose up -d --build

  compose-down:
    cmds:
      - docker compose down

  migrate-up:
    cmds:
      - ./scripts/tasks/migrate-up.sh

  migrate-down:
    cmds:
      - ./scripts/tasks/migrate-down.sh

  migrate-force:
    cmds:
      - ./scripts/tasks/migrate-force.sh
